# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Tests Enterprise

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Cache docker images
      uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
      with:
        key: ${{ runner.os }}-docker-layer-cache-${{ matrix.tarantool-version }}
        restore-keys: |
          ${{ runner.os }}-docker-layer-cache-

    - name: Run enterprise tests
      env:
        TARANTOOL_VERSION: ${{ matrix.tarantool-version }}
        TARANTOOL_SERVER_USER: root
        TARANTOOL_SERVER_GROUP: root
        DOWNLOAD_SDK_URI: https://tarantool:${{ secrets.DOWNLOAD_SDK_TOKEN }}@download.tarantool.io/enterprise/release/linux/x86_64/2.10
        SDK_VERSION: tarantool-enterprise-sdk-nogc64-2.10.4-0-r523.linux.x86_64
      run: mvn -B test -P enterprise --file pom.xml
